CREATE TABLE "model_benchmark_snapshots" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"provider_id" text NOT NULL,
	"model_id" text NOT NULL,
	"model_display_name" text NOT NULL,
	"source_model_id" text,
	"source_model_slug" text,
	"model_creator_id" text,
	"model_creator_name" text,
	"model_creator_slug" text,
	"evaluations" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"pricing" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"artificial_analysis_intelligence_index" numeric,
	"artificial_analysis_coding_index" numeric,
	"artificial_analysis_math_index" numeric,
	"mmlu_pro" numeric,
	"gpqa" numeric,
	"hle" numeric,
	"livecodebench" numeric,
	"scicode" numeric,
	"math_500" numeric,
	"aime" numeric,
	"median_output_tokens_per_second" numeric,
	"median_time_to_first_token_seconds" numeric,
	"median_time_to_first_answer_token_seconds" numeric,
	"source_name" text NOT NULL,
	"source_confidence" text NOT NULL,
	"fetched_at" timestamp with time zone NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
